pipeline {
    agent any
    stages{
        stage('vcs') {
            steps {
                git url: 'https://github.com/divyakothuru311/CICD-TERRAFORM.g',
                       branch: 'main'
            }
        }
        stage('create vm via terraform') {
            steps {
                sh 'terraform init'
                sh 'terraform validate'
                sh 'terraform apply -auto-approve'
            }
        }
    }
}